sqlite3:
  database: ":memory:"
  adapter: sqlite3
  timeout: 500

mysql:
  adapter: mysql
  database: has_magic_columns
  username: 
  encoding: utf8

mysql2:
  adapter: mysql2
  database: has_magic_columns
  username: 
  encoding: utf8

postgres:
  adapter: postgresql
  database: has_magic_columns
  username: postgres
  min_messages: warning

